<table style="margin-top: 4px; border-top: 1px solid #e5e7eb; padding-top: 1px;">
    <tr>
        <td style="width: 50%; padding-left: 0;">
            <div class="footer-text">
                This document was automatically generated by Machine Report CMMS.<br/>
                Document Number: <strong style="color: #4b5563;">{{ $doc_number }}</strong> &nbsp;|&nbsp; Revision: <strong>{{ $revision }}</strong>
            </div>
        </td>
        <td style="width: 50%; text-align: right; padding-right: 0;">
            <div class="footer-text">
                Generated: <strong>{{ $generation_time }}</strong><br/>
                Printed: <strong>{{ $print_time }}</strong>
            </div>
        </td>
    </tr>
</table>
